### ISSUE TITLE
Validation Data Generator Error

### ISSUE THREAD

**Issue by gitmedenis** [Socret360/object-detection-in-keras#3]
https://github.com/Socret360/object-detection-in-keras/blob/eef3e06bf9811375da3335fbfd7a7f0be0852e79/utils/training_utils/get_data_generator.py#L20

I believe "split_file=args.training_split" should be "split_file=args.validation_split". FYI.

**Comment by Socret360** [comment]
Yes it should. My mistake. I'll make changes accordingly. Thank you
